#!/bin/bash

build() {
    if [ -f /etc/default/ps4 ]; then
        add_file /etc/default/ps4
    fi

    add_runscript
}


help() {
    cat <<HELPEOF
This hook mount ps4 internal HDD
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
